name: default
render_width: 1000
render_height: 1000
camera_translation: [0, 0.65, 2]
camera_angle: 15
orthographic_camera: False
smooth: False
asset_idx: 2
frame_idx: -1
show_rendering: True
make_gif: False
render_frames: 1
gif_fps: 20
show_from_behind: False
show_sideways: False
show_body: True
show_vertex_distance: False
show_gt: False
acc_delta: -1
body_transparency: 0.0   # [0,1.0]
show_joints: False
show_skeleton: False
show_sensors: True
show_sensor_orientations: False
show_accelerations: False
show_markers: False
use_default_pose: True
use_relaxed_pose: False
render_every_n_frame: 30
sensors: all
show_unused_sensors: False
sensor_config: SSP
real_data: False
source: None
render_every_n_frame_gif: 2
transparent_background: True
show_world_axes: False
show_model_axes: False
show_joint_axes: False

eval_rkk_studio: False

#dataset:
#  source: AMASS
#  sensor_config: SSP
#  fps: 100
#  synthesis:
#    acc_noise: 0
#    gyro_noise: 0
#    acc_delta: 4
