defaults:
  - default

name: body_with_sensors
render_width: 600
render_height: 800
show_rendering: True
orthographic_camera: True
use_relaxed_pose: True
use_default_pose: False
show_from_behind: True
#show_sensor_orientations: True
body_transparency: 0.7
camera_translation: [0, -.1, 1.5]
camera_angle: 0.0
show_unused_sensors: True
sensors:
 - left_pelvis
 - right_pelvis
 - left_back
 - right_back
 - left_collar
 - right_collar
# - head
 - left_shoulder
 - right_shoulder
 - left_elbow
 - right_elbow
 - left_wrist
 - right_wrist
 - left_hip
 - right_hip
 - left_knee
 - right_knee
 - left_ankle
 - right_ankle

