experiment_name: baseline
training_sensors:
  config: SSP
  count: 17
  names:
    - left_back
    - right_back
    - left_collar
    - right_collar
    - head
    - left_shoulder
    - right_shoulder
    - left_elbow
    - right_elbow
    - left_wrist
    - right_wrist
    - left_hip
    - right_hip
    - left_knee
    - right_knee
    - left_ankle
    - right_ankle
train_params:
  ds_type: synthetic
  batch_size_training: 16
  max_epochs: 80
  early_stopping_tolerance: 10
  training_evaluate_every_step: 500
  grad_clip_norm: 10
