debug: False
defaults:
 - experiment: baseline
 - hyperparams: default
 - override hydra/job_logging: disabled
 - override hydra/hydra_logging: disabled
# - override hydra/launcher: submitit_local
 - override hydra/launcher: submitit_slurm


hydra:
#  setup for slurm
  launcher:
    timeout_min: 300
    cpus_per_task: 1
    mem_gb: 2
    additional_parameters: {"partition": "gpu", "gres": "gpu:titanrtx:1", "mail-user": "nickueng@gmail.com", "mail-type": "BEGIN,END,FAIL,TIME_LIMIT_80"}
    array_parallelism: 4

  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .
