debug: False
gpu: True
traintime_noise: False
noise: 0.001
finetune: True
defaults:
  - experiment: SSP_19
  - hyperparams: default
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .
