debug: False
defaults:
 - experiment: baseline
 - hyperparams: default
 - override hydra/job_logging: disabled
 - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .
